builds:
  - main: ./cmd/kafta
    id: "kafta"
    binary: kafta
    goos:
      - linux

before:
  hooks:
    - make build

release:
  github:
    owner: lucasviecelli
    name: https://github.com/electric-saw/kafta
  name_template: "{{.ProjectName}}-v{{.Version}}"